DATA CLEANING

In [1]:
# Basic Libraries
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt 
%matplotlib inline
import json

IMPORT DATA SET

In [2]:

raw_data = pd.read_csv('movie1.csv')
raw_data.head(50)

,ID,FILMID,TITLE,ADULT,BACKDROP_PATH,BUDGET,HOMEPAGE,IMDB_ID,ORIGINAL_LANGUAGE,ORIGINAL_TITLE,...,POPULARITY,POSTER_PATH,RELEASE_DATE,REVENUE,RUNTIME,VOTE_AVERAGE,VOTE_COUNT,STATUS_,TAGLINE,COLLECTIONID
0,1,741067,Welcome to Sudden Death,False,/aO5ILS7qnqtFIprbJ40zla0jhpu.jpg,0,https://xmovies8.app/,tt10804786,en,Welcome to Sudden Death,...,1892.824,/elZ6JCzSEvFOq4gNjNeZsnRFsvj.jpg,29/9/2020,0,80.0,6.8,100,Released,NaN,NaN
1,2,497582,Enola Holmes,False,/kMe4TKMDNXTKptQPAdOF0oZHq3V.jpg,21000000,https://www.netflix.com/title/81277950,tt7846844,en,Enola Holmes,...,1317.089,/riYInlsq2kf1AWoGm80JQW5dLKp.jpg,23/9/2020,0,123.0,7.6,1965,Released,Mystery runs in the family.,NaN
2,3,749544,Brutal Bridesmaids,False,NaN,0,NaN,tt12318720,en,Brutal Bridesmaids,...,38.034,/pNzOWfwZxZzfEYxU2vXGyc77Jz8.jpg,15/10/2020,0,0.0,0.0,0,Released,Dealing with bridesmaids can be killer.,NaN
3,4,669666,Home,False,NaN,0,NaN,tt10353704,en,Home,...,28.930,NaN,15/10/2020,0,0.0,0.0,0,Released,NaN,NaN
4,5,528085,2067,False,/5UkzNSOK561c2QRy2Zr4AkADzLT.jpg,0,http://screen.nsw.gov.au/project/2067,tt1918734,en,2067,...,1549.992,/7D430eqZj8y3oVkLFfsWXGRcpEG.jpg,1/10/2020,0,114.0,5.7,103,Released,The fight for the future has begun.,NaN
5,6,660982,American Pie Presents: Girls Rules,False,/75ooojtgiKYm5LcCczbCexioZze.jpg,0,NaN,tt11771594,en,American Pie Presents: Girls' Rules,...,931.299,/ov1sd4gvHpoVheHuJHCXJjadeIT.jpg,6/10/2020,0,95.0,6.4,64,Released,NaN,NaN
6,7,748680,The Story Of Xi Bao,False,NaN,0,NaN,tt13180792,zh,喜宝,...,16.243,/irhRJLorG0cVU8vydC9a3AMQ63S.jpg,16/10/2020,0,0.0,0.0,0,Released,NaN,NaN
7,8,337401,Mulan,False,/zzWGRw277MNoCs3zhyG3YmYQsXv.jpg,200000000,https://movies.disney.com/mulan-2020d,tt4566758,en,Mulan,...,936.725,/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg,4/9/2020,57000000,115.0,7.3,2445,Released,NaN,NaN
8,9,724989,Hard Kill,False,/86L8wqGMDbwURPni2t7FQ0nDjsH.jpg,0,NaN,tt11656172,en,Hard Kill,...,867.477,/ugZW8ocsrfgI95pnQ7wrmKDxIe.jpg,25/8/2020,0,98.0,4.7,138,Released,Take on a madman. Save the world.,NaN
9,10,694919,Money Plane,False,/pq0JSpwyT2URytdFG0euztQPAyR.jpg,0,http://essaymonkey.net/,tt7286966,en,Money Plane,...,880.735,/6CoRTJTmijhBLJTUNoVSUNxZMEI.jpg,29/9/2020,0,82.0,6.1,135,Released,NaN,NaN
10,11,539885,Ava,False,/54yOImQgj8i85u9hxxnaIQBRUuo.jpg,0,http://essaymonkey.net/,tt8784956,en,Ava,...,744.393,/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg,2/7/2020,152812,96.0,5.9,473,Released,Kill. Or be killed.,NaN
11,12,697064,Beckman,False,/7WKIOXJa2JjHygE8Yta3uaCv6GC.jpg,1200000,NaN,tt10989808,en,Beckman,...,748.318,/z0r3YjyJSLqf6Hz0rbBAnEhNXQ7.jpg,10/9/2020,0,90.0,6.1,4,Released,A mission of vengeance.,NaN
12,13,617505,Hubie Halloween,False,/aOeshAxAhiDVIiHsXVFmF6bgclh.jpg,14000000,https://www.netflix.com/title/80245104,tt10682266,en,Hubie Halloween,...,682.451,/uQnqhfxWaw2fN3bgpDbO0RVFHLF.jpg,7/10/2020,0,102.0,6.4,362,Released,Fear. Less.,NaN
13,14,718444,Rogue,False,/x4UkhIQuHIJyeeOTdcbZ3t3gBSa.jpg,0,NaN,tt11576124,en,Rogue,...,733.270,/uOw5JD8IlD546feZ6oxbIjvN66P.jpg,20/8/2020,0,106.0,5.9,301,Released,When the hunter becomes the prey.,NaN
14,15,734309,Santana,False,/7fvdg211A2L0mHddvzyArRuRalp.jpg,2600000,https://www.netflix.com/title/81249503,tt11769162,en,Santana,...,708.813,/9Rj8l6gElLpRL7Kj17iZhrT5Zuw.jpg,28/8/2020,0,106.0,5.6,136,Released,"Two brothers, both cops. One wants justice, th...",NaN
15,16,581392,Peninsula,False,/gEjNlhZhyHeto6Fy5wWy5Uk3A9D.jpg,17000000,https://www.wellgousa.com/films/train-to-busan...,tt8850222,ko,반도,...,641.633,/sy6DvAu72kjoseZEjocnm2ZZ09i.jpg,15/7/2020,35878266,114.0,7.1,602,Released,Escape The Apocalypse,619537.0
16,17,623634,The Innocence,False,/fbjzxbWAUijs0fsQ6Hlbls0NtAj.jpg,0,NaN,tt8872580,ca,La innòcencia,...,448.451,/qOYf3L6eyCO027JoeM33pTJcNSR.jpg,10/1/2020,0,92.0,6.4,42,Released,It's summertime. And the living is easy...,NaN
17,18,621870,Secret Society of Second Born Royals,False,/oSSEcPDfwgZSv2i01Oqxdb9t8fI.jpg,0,NaN,tt10324122,en,Secret Society of Second Born Royals,...,562.965,/xOmGTJtBgRVSAF4S5dZEUqHqyy5.jpg,25/9/2020,0,97.0,7.0,153,Released,Born to defend. They just have to learn how.,NaN
18,19,475430,Artemis Fowl,False,/o0F8xAt8YuEm5mEZviX5pEFC12y.jpg,125000000,https://movies.disney.com/artemis-fowl,tt3089630,en,Artemis Fowl,...,572.472,/tI8ocADh22GtQFV28vGHaBZVb0U.jpg,12/6/2020,0,95.0,5.8,869,Released,Remember the name,NaN
19,20,438396,Unknown Origins,False,/qGZe9qTuydxyJYQ60XDtEckzLR8.jpg,3268650,http://www.quexito.com/en/portfolio-items/orig...,tt5827790,es,Orígenes secretos,...,552.734,/vJHSParlylICnI7DuuI54nfTPRR.jpg,28/8/2020,0,97.0,6.2,213,Released,NaN,NaN
20,21,606234,Archive,False,/u9YEh2xVAPVTKoaMNlB5tH6pXkm.jpg,0,NaN,tt6882604,en,Archive,...,514.435,/eDnHgozW8vfOaLHzfpHluf1GZCW.jpg,13/8/2020,0,109.0,5.7,129,Released,Death is not the end,NaN
21,22,721452,One Night in Bangkok,False,/riDrpqQtZpXGeiJdlmfcwwPH7nN.jpg,0,NaN,tt12192190,en,One Night in Bangkok,...,469.442,/i4kPwXPlM1iy8Jf3S1uuLuwqQAV.jpg,25/8/2020,0,105.0,7.2,108,Released,Six Hours. Five Hits. Who Will Survive?,NaN
22,23,76600,Avatar 2,False,/z3ElnHwcf1g56Qlp53yGbPsGXL7.jpg,387000000,http://www.avatarmovie.com/,tt1630029,en,Avatar 2,...,13.432,NaN,15/12/2022,0,0.0,0.0,0,Post Production,NaN,87096.0
23,24,726739,Cats & Dogs 3: Paws Unite,False,/t22fWbzdnThPseipsdpwgdPOPCR.jpg,0,NaN,tt12745164,en,Cats & Dogs 3: Paws Unite,...,443.937,/4BgSWFMW2MJ0dT5metLzsRWO7IJ.jpg,2/10/2020,0,84.0,6.5,66,Released,NaN,87014.0
24,25,605116,Project Power,False,/qVygtf2vU15L2yKS4Ke44U4oMdD.jpg,0,http://www.netflix.com/projectpower,tt7550000,en,Project Power,...,434.633,/TnOeov4w0sTtV2gqICqIxVi74V.jpg,14/8/2020,0,113.0,6.6,1419,Released,What would you risk for five minutes of pure p...,NaN
25,26,746957,You've Got This,False,/3elhhPDPSD3m0T0SQDJN00O6WhQ.jpg,0,http://www.netflix.com/title/81050943,tt13118012,es,Ahí te encargo,...,432.761,/2bN7DbfJHrgOAnGLRuQUmImDaqY.jpg,2/10/2020,0,111.0,8.5,113,Released,NaN,NaN
26,27,677638,We Bare Bears: The Movie,False,/pO1SnM5a1fEsYrFaVZW78Wb0zRJ.jpg,0,NaN,tt10474606,en,We Bare Bears: The Movie,...,414.863,/kPzcvxBwt7kEISB9O4jJEuBn72t.jpg,30/6/2020,0,69.0,7.7,443,Released,NaN,NaN
27,28,715123,Books of Blood,False,/g6qb2h3dT1tb0zkhktD5r7ZHbmp.jpg,0,https://www.hulu.com/movie/books-of-blood-a580...,tt11242218,en,Books of Blood,...,336.974,/bXLVZGgLgd7OwbfP6fC5GCfrxuD.jpg,7/10/2020,0,107.0,6.3,17,Released,All stories end here.,NaN
28,29,613504,After We Collided,False,/r5srC0cqU36n38azFnCyReEksiR.jpg,0,NaN,tt10362466,en,After We Collided,...,371.194,/kiX7UYfOpYrMFSAGbI6j1pFkLzQ.jpg,2/9/2020,0,105.0,6.5,460,Released,Can love overcome the past?,702624.0
29,30,594328,Phineas and Ferb The Movie: Candace Against th...,False,/lkeBhXGJFRlhI7cBWn8LQQAdZqK.jpg,0,NaN,tt1817232,en,Phineas and Ferb The Movie: Candace Against th...,...,386.237,/n6hptKS7Y0ZjkYwbqKOK3jz9XAC.jpg,28/8/2020,0,84.0,7.1,114,Released,Get ready for a mission that's out of this world!,715146.0
30,31,716258,Black Box,False,/1fOwb62XudDlevVyu1rqUlHUrES.jpg,0,https://www.amazon.com/dp/B08DX974X5,tt12298506,en,Black Box,...,290.285,/9Z1zkb4Z9hUlEuC0oMagVJaPUeS.jpg,6/10/2020,0,100.0,6.5,61,Released,There is no escape from who you really are.,NaN
31,32,722603,Battlefield 2025,False,/m7QpUAeI2xTCJyAVl9J9z5dBTSb.jpg,0,NaN,tt8134980,en,Battlefield 2025,...,362.620,/w6e0XZreiyW4mGlLRHEG8ipff7b.jpg,7/7/2020,0,0.0,5.7,67,Released,Fighting for our survival.,NaN
32,33,495764,Birds of Prey (and the Fantabulous Emancipatio...,False,/9xNOiv6DZZjH7ABoUUDP0ZynouU.jpg,75000000,http://www.birdsofpreymovie.net,tt7713068,en,Birds of Prey (and the Fantabulous Emancipatio...,...,361.237,/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg,5/2/2020,201858461,109.0,7.2,6022,Released,Mind Over Mayhem,NaN
33,34,385103,Scoob!,False,/fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg,0,https://www.scoob.movie/,tt3152592,en,Scoob!,...,335.013,/jHo2M1OiH9Re33jYtUQdfzPeUkx.jpg,8/7/2020,9430580,94.0,7.4,759,Released,Mystery loves company.,NaN
34,35,38700,Bad Boys for Life,False,/upUy2QhMZEmtypPW3PdieKLAHxh.jpg,90000000,https://www.badboysforlife.movie/,tt1502397,en,Bad Boys for Life,...,337.346,/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg,15/1/2020,419074646,124.0,7.2,5392,Released,Ride together. Die together.,14890.0
35,36,741998,The Binding,False,/tOOfXpIKyY80kY108pwSgLozgRA.jpg,0,https://www.netflix.com/title/81245546,tt10914452,it,Il legame,...,249.792,/k8Oj2YlFKbwj1SNKZcb5Fw1Yosj.jpg,2/10/2020,0,93.0,5.6,79,Released,NaN,NaN
36,37,703134,Infamous,False,/j57oUw8LIYvjOl0zs3A1A1UqwKH.jpg,0,https://www.sssentertainment.com/infamous,tt7703924,en,Infamous,...,328.587,/q2lkJf1TAjImTHCEO7XvbqPtnPb.jpg,12/6/2020,0,100.0,5.4,41,Released,Viral fame is a dangerous game.,NaN
37,38,531499,The Tax Collector,False,/zogWnCSztU8xvabaepQnAwsOtOt.jpg,30000000,NaN,tt8461224,en,The Tax Collector,...,309.223,/3eg0kGC2Xh0vhydJHO37Sp4cmMt.jpg,7/8/2020,0,95.0,6.1,147,Released,Payback comes with interest.,NaN
38,39,547016,The Old Guard,False,/m0ObOaJBerZ3Unc74l471ar8Iiy.jpg,70000000,https://www.netflix.com/title/81038963,tt7556122,en,The Old Guard,...,327.513,/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg,10/7/2020,0,124.0,7.3,2138,Released,Forever is harder than it looks,NaN
39,40,632618,The Crimes That Bind,False,/cVdYaAQmd5DZNdo0KFJruz7JpUs.jpg,0,https://www.netflix.com/title/81227758,tt10915060,es,Crímenes de familia,...,327.588,/sDi6wKgECUjDug2gn4uODSqZ3yC.jpg,20/8/2020,0,99.0,6.5,114,Released,NaN,NaN
40,41,611395,Double World,False,/90yhXKTDNfaV7JnC7RcTpZcRTGC.jpg,42835740,NaN,tt10508838,zh,征途,...,309.826,/lv3RonWge4GlC9ymNzC0oWpFCfv.jpg,21/7/2020,0,110.0,6.8,120,Released,NaN,NaN
41,42,446893,Trolls World Tour,False,/qsxhnirlp7y4Ae9bd11oYJSX59j.jpg,0,https://www.dreamworks.com/movies/trolls-world...,tt6587640,en,Trolls World Tour,...,308.614,/7W0G3YECgDAfnuiHG91r8WqgIOe.jpg,12/3/2020,1946164,91.0,7.6,1203,Released,NaN,489724.0
42,44,338762,Bloodshot,False,/lP5eKh8WOcPysfELrUpGhHJGZEH.jpg,42000000,https://www.bloodshot.movie/,tt1634106,en,Bloodshot,...,253.895,/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg,5/3/2020,30234182,110.0,7.0,3216,Released,Being a superhero is in his blood,NaN
43,45,508439,Onward,False,/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg,200000000,NaN,tt7146812,en,Onward,...,279.470,/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg,29/2/2020,103181419,102.0,7.9,3243,Released,Their quest begineth.,NaN
44,46,425001,The War with Grandpa,False,/4gKyQ1McHa8ZKDsYoyKQSevF01J.jpg,0,https://warwithgrandpa.com/,tt4532038,en,The War with Grandpa,...,268.898,/ltyARDw2EFXZ2H2ERnlEctXPioP.jpg,27/8/2020,0,94.0,6.1,75,Released,Old school vs new cool,NaN
45,47,738215,Barbie: Princess Adventure,False,/cmZVWuXM1hpP2GKFABCUkoscKu4.jpg,0,https://www.netflix.com/title/81136524,tt12767498,en,Barbie: Princess Adventure,...,267.498,/AwkmMTKJBAatbeAVhTwhcU3Pyp4.jpg,1/9/2020,0,72.0,7.7,64,Released,NaN,NaN
46,48,664767,Mortal Kombat Legends: Scorpion's Revenge,False,/9xeEGUZjgiKlI69jwIOi0hjKUIk.jpg,0,https://www.warnerbros.com/movies/mortal-komba...,tt9580138,en,Mortal Kombat Legends: Scorpion's Revenge,...,251.189,/4VlXER3FImHeFuUjBShFamhIp9M.jpg,12/4/2020,0,80.0,8.4,631,Released,NaN,9818.0
47,49,454626,Sonic the Hedgehog,False,/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg,85000000,https://www.paramountmovies.com/movies/sonic-t...,tt3794354,en,Sonic the Hedgehog,...,340.193,/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg,12/2/2020,306766470,99.0,7.5,5877,Released,A Whole New Speed of Hero,720879.0
48,50,601165,Legacy of Lies,False,/nxxODhq9I05Ze9uLONGvfDrzaUO.jpg,0,NaN,tt6834916,en,Legacy of Lies,...,299.204,/bhNHCeJDFDaB00A46AoCw2mggdE.jpg,6/8/2020,0,101.0,5.9,85,Released,He's afraid of nothing... except the truth.,NaN
49,51,516486,Greyhound,False,/xXBnM6uSTk6qqCf0SRZKXcga9Ba.jpg,50300000,https://tv.apple.com/movie/greyhound/umc.cmc.o...,tt6048922,en,Greyhound,...,284.899,/kjMbDciooTbJPofVXgAoFjfX8Of.jpg,10/7/2020,0,91.0,7.5,1248,Released,The only thing more dangerous than the front l...,NaN

In [3]:
# Inforamtion about the Variables
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159725 entries, 0 to 159724
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ID                 159725 non-null  int64
 1   FILMID             159725 non-null  int64
 2   TITLE              159725 non-null  object
 3   ADULT              159725 non-null  bool
 4   BACKDROP_PATH      58724 non-null   object
 5   BUDGET             159725 non-null  int64
 6   HOMEPAGE           15848 non-null   object
 7   IMDB_ID            149399 non-null  object
 8   ORIGINAL_LANGUAGE  159725 non-null  object
 9   ORIGINAL_TITLE     159725 non-null  object
 10  OVERVIEW           135783 non-null  object
 11  POPULARITY         159725 non-null  float64
 12  POSTER_PATH        115972 non-null  object
 13  RELEASE_DATE       159725 non-null  object
 14  REVENUE            159725 non-null  int64
 15  RUNTIME            147646 non-null  float64
 16  VOTE_AVERAGE       159725 non-null  float64
 17  VOTE_COUNT         159725 non-null  int64
 18  STATUS_            159725 non-null  object
 19  TAGLINE            39254 non-null   object
 20  COLLECTIONID       8875 non-null    float64
dtypes: bool(1), float64(4), int64(5), object(11)
memory usage: 24.5+ MB

In [4]:
# describe our data
raw_data.describe()

,ID,FILMID,BUDGET,POPULARITY,REVENUE,RUNTIME,VOTE_AVERAGE,VOTE_COUNT,COLLECTIONID
count,159725.000000,159725.000000,1.597250e+05,159725.000000,1.597250e+05,147646.000000,159725.000000,159725.000000,8875.000000
mean,82088.733774,281378.185187,1.445012e+06,3.499204,3.823041e+06,76.785128,3.930748,82.876676,323964.750648
std,48321.091408,205582.337660,1.046781e+07,13.105463,3.953710e+07,56.707768,3.081387,619.855920,224863.612360
min,1.000000,2.000000,0.000000e+00,0.600000,0.000000e+00,0.000000,0.000000,0.000000,10.000000
25%,40345.000000,85837.000000,0.000000e+00,0.700000,0.000000e+00,58.000000,0.000000,0.000000,118086.500000
50%,81099.000000,265933.000000,0.000000e+00,1.400000,0.000000e+00,89.000000,5.000000,2.000000,304809.000000
75%,122638.000000,437083.000000,0.000000e+00,3.286000,0.000000e+00,100.000000,6.400000,9.000000,499070.000000
max,167601.000000,753790.000000,3.870000e+08,1892.824000,2.797801e+09,12480.000000,10.000000,27342.000000,756652.000000

Drop unused columns in the analysis

In [5]:
raw_data.drop(['ID', 'FILMID', 'TITLE', 
               'ADULT', 'BACKDROP_PATH','HOMEPAGE','IMDB_ID','ORIGINAL_TITLE', 'OVERVIEW',
               'POSTER_PATH','STATUS_','TAGLINE','COLLECTIONID','ORIGINAL_LANGUAGE'],axis=1,inplace=True)
raw_data.head(20)

,BUDGET,POPULARITY,RELEASE_DATE,REVENUE,RUNTIME,VOTE_AVERAGE,VOTE_COUNT
0,0,1892.824,29/9/2020,0,80.0,6.8,100
1,21000000,1317.089,23/9/2020,0,123.0,7.6,1965
2,0,38.034,15/10/2020,0,0.0,0.0,0
3,0,28.930,15/10/2020,0,0.0,0.0,0
4,0,1549.992,1/10/2020,0,114.0,5.7,103
5,0,931.299,6/10/2020,0,95.0,6.4,64
6,0,16.243,16/10/2020,0,0.0,0.0,0
7,200000000,936.725,4/9/2020,57000000,115.0,7.3,2445
8,0,867.477,25/8/2020,0,98.0,4.7,138
9,0,880.735,29/9/2020,0,82.0,6.1,135
10,0,744.393,2/7/2020,152812,96.0,5.9,473
11,1200000,748.318,10/9/2020,0,90.0,6.1,4
12,14000000,682.451,7/10/2020,0,102.0,6.4,362
13,0,733.270,20/8/2020,0,106.0,5.9,301
14,2600000,708.813,28/8/2020,0,106.0,5.6,136
15,17000000,641.633,15/7/2020,35878266,114.0,7.1,602
16,0,448.451,10/1/2020,0,92.0,6.4,42
17,0,562.965,25/9/2020,0,97.0,7.0,153
18,125000000,572.472,12/6/2020,0,95.0,5.8,869
19,3268650,552.734,28/8/2020,0,97.0,6.2,213

Drop zero value row

In [6]:
print("Rows with none zero values in Budget: ", raw_data[(raw_data['BUDGET']!=0)].shape[0])
print("Rows with none zero values in Revenue: ", raw_data[(raw_data['REVENUE']!=0)].shape[0])
print("Rows with none zero values in Vote_count: ", raw_data[(raw_data['VOTE_COUNT']!=0)].shape[0])
print("Rows with none zero values in POPULARITY: ", raw_data[(raw_data['POPULARITY']!=0)].shape[0])


# DROP data with value less than 0
raw_data = raw_data.loc[(raw_data[['REVENUE',"BUDGET", "VOTE_COUNT", "POPULARITY"]]>0).all(axis=1)]

Rows with none zero values in Budget:  12792
Rows with none zero values in Revenue:  9791
Rows with none zero values in Vote_count:  105019
Rows with none zero values in POPULARITY:  159725

In [7]:
# describe our data
raw_data.head()

,BUDGET,POPULARITY,RELEASE_DATE,REVENUE,RUNTIME,VOTE_AVERAGE,VOTE_COUNT
7,200000000,936.725,4/9/2020,57000000,115.0,7.3,2445
15,17000000,641.633,15/7/2020,35878266,114.0,7.1,602
32,75000000,361.237,5/2/2020,201858461,109.0,7.2,6022
34,90000000,337.346,15/1/2020,419074646,124.0,7.2,5392
42,42000000,253.895,5/3/2020,30234182,110.0,7.0,3216

SPILT RELEASE DATE INTO YEAR AND MONTH

In [8]:
raw_data['RELEASE_DATE'] = pd.to_datetime(raw_data['RELEASE_DATE'])
raw_data['RELEASE_DATE'].head(50)

7     2020-04-09
15    2020-07-15
32    2020-05-02
34    2020-01-15
42    2020-05-03
43    2020-02-29
47    2020-12-02
60    2019-01-08
65    2019-12-25
67    2019-11-20
72    2014-01-30
74    2017-10-27
77    2018-04-25
79    2019-12-19
80    2020-02-09
84    2019-04-12
87    2019-06-28
88    2019-04-24
96    2001-07-12
97    2014-09-18
98    2005-06-29
99    2008-11-21
100   2009-04-26
101   2014-12-11
102   2019-03-07
104   2019-11-04
105   2019-05-22
111   2019-12-07
116   2020-08-22
117   2019-10-10
120   2019-05-15
121   2013-07-08
124   2018-03-01
125   2010-01-21
129   2002-10-25
132   2019-04-09
137   2002-10-18
140   2019-09-10
148   2003-09-19
151   2008-01-07
152   2004-10-29
153   2002-02-10
155   2020-01-01
156   2019-03-05
160   2019-12-18
163   2020-08-26
166   2018-06-12
170   2018-11-20
172   2019-08-22
174   2019-09-19
Name: RELEASE_DATE, dtype: datetime64[ns]

In [9]:
# Extract year and month of release date and Put into new columns
raw_data['release_year'] = raw_data['RELEASE_DATE'].dt.year
raw_data['release_month'] = raw_data['RELEASE_DATE'].dt.month

# Drop release_date columns
raw_data.drop(['RELEASE_DATE'],axis=1,inplace=True)
raw_data = raw_data.reset_index(drop=True)

# Fill NA/NaN values using 0
raw_data['release_year'] = raw_data['release_year'].fillna(0)
raw_data['release_month'] = raw_data['release_month'].fillna(0)

# Convert dtypes of columns
raw_data['release_year'] = raw_data['release_year'].astype('int64')
raw_data['release_month'] = raw_data['release_month'].astype('category')

display(raw_data['release_year'].describe())
display(raw_data['release_month'].describe())

count    6667.000000
mean     2000.409030
std        16.699905
min      1900.000000
25%      1994.000000
50%      2005.000000
75%      2012.000000
max      2020.000000
Name: release_year, dtype: float64

count     6667
unique      12
top         12
freq       686
Name: release_month, dtype: int64

In [10]:
raw_data.head(100)

,BUDGET,POPULARITY,REVENUE,RUNTIME,VOTE_AVERAGE,VOTE_COUNT,release_year,release_month
0,200000000,936.725,57000000,115.0,7.3,2445,2020,4
1,17000000,641.633,35878266,114.0,7.1,602,2020,7
2,75000000,361.237,201858461,109.0,7.2,6022,2020,5
3,90000000,337.346,419074646,124.0,7.2,5392,2020,1
4,42000000,253.895,30234182,110.0,7.0,3216,2020,5
...,...,...,...,...,...,...,...,...
95,135000000,90.240,587204668,98.0,6.9,4874,2013,3
96,250000000,88.028,933959197,153.0,7.7,13414,2009,7
97,160000000,83.605,1148461807,144.0,6.9,9406,2018,7
98,150000000,96.360,259239658,164.0,7.5,8790,2017,4
99,28000000,91.249,39514713,96.0,6.9,1615,1993,7

Drop movies that are produced earlier than 1990

In [11]:
print("Rows with year under 1990: ", raw_data[(raw_data['release_year']<1990)].shape[0])


# DROP data with value less than 0
raw_data = raw_data.loc[raw_data['release_year']>=1990]
raw_data = raw_data.reset_index(drop=True)

Rows with year under 1990:  1251

In [12]:
raw_data.describe()

,BUDGET,POPULARITY,REVENUE,RUNTIME,VOTE_AVERAGE,VOTE_COUNT,release_year
count,5.416000e+03,5416.000000,5.416000e+03,5416.000000,5416.000000,5416.000000,5416.000000
mean,3.456561e+07,19.398283,9.838571e+07,109.115214,6.328619,1695.707349,2006.813516
std,4.263966e+07,26.162331,1.865449e+08,21.322490,0.901775,2767.024743,7.780242
min,1.000000e+00,0.600000,1.000000e+00,0.000000,0.000000,1.000000,1990.000000
25%,7.000000e+06,9.301250,6.414526e+06,95.000000,5.800000,174.000000,2001.000000
50%,2.000000e+07,13.602000,3.098968e+07,105.000000,6.400000,658.500000,2008.000000
75%,4.500000e+07,21.862000,1.064767e+08,120.000000,6.900000,1950.750000,2013.000000
max,3.800000e+08,936.725000,2.797801e+09,339.000000,10.000000,27342.000000,2020.000000

In [13]:
#inflation rate from 1990 to 2022
#Inflation rate from https://www.calculator.net/inflation-calculator.html?cstartingamount1=100&cinyear1=1990&coutyear1=2022&calctype=1&x=93&y=21
inflation = [2.1876, 2.0757, 1.9911, 1.9326 ,1.877, 1.8292, 1.7793, 1.7286, 1.6891, 1.6633,  1.6277,
             1.5744, 1.5311, 1.5071, 1.4737, 1.4352, 1.3882, 1.3446, 1.3073, 1.2589, 1.2632, 1.2428,
             1.2047, 1.1803, 1.1632, 1.1456, 1.1433, 1.129, 1.1055, 1.0792, 1.06, 1.047, 1]

#Adjust revenue according to inflation

In [14]:
adjusted_revenue = []
adjusted_budget = []
for index, rows in raw_data.iterrows():
    adjusted_budget.append(int(rows['BUDGET'] * inflation[round(rows['release_year']-1990)]))
    adjusted_revenue.append(int(rows['REVENUE'] * inflation[round(rows['release_year']-1990)]))
    
    
adjusted_budget = pd.DataFrame(adjusted_budget, columns = ['New_Budget'])
adjusted_revenue = pd.DataFrame(adjusted_revenue, columns = ['New_Revenue'])

raw_data = pd.concat([raw_data, adjusted_budget, adjusted_revenue], axis = 1)

In [15]:
raw_data.head()

,BUDGET,POPULARITY,REVENUE,RUNTIME,VOTE_AVERAGE,VOTE_COUNT,release_year,release_month,New_Budget,New_Revenue
0,200000000,936.725,57000000,115.0,7.3,2445,2020,4,212000000,60420000
1,17000000,641.633,35878266,114.0,7.1,602,2020,7,18020000,38030961
2,75000000,361.237,201858461,109.0,7.2,6022,2020,5,79500000,213969968
3,90000000,337.346,419074646,124.0,7.2,5392,2020,1,95400000,444219124
4,42000000,253.895,30234182,110.0,7.0,3216,2020,5,44520000,32048232

#Round up/down the vote_average to whole number

In [16]:
adjusted_vote_avg=[]
for index, rows in raw_data.iterrows():
    adjusted_vote_avg.append(round(rows['VOTE_AVERAGE']))

adjusted_vote_avg= pd.DataFrame(adjusted_vote_avg, columns=["New_Vote_Avg"])

raw_data = pd.concat([raw_data, adjusted_vote_avg], axis = 1)
raw_data.head(100)

,BUDGET,POPULARITY,REVENUE,RUNTIME,VOTE_AVERAGE,VOTE_COUNT,release_year,release_month,New_Budget,New_Revenue,New_Vote_Avg
0,200000000,936.725,57000000,115.0,7.3,2445,2020,4,212000000,60420000,7
1,17000000,641.633,35878266,114.0,7.1,602,2020,7,18020000,38030961,7
2,75000000,361.237,201858461,109.0,7.2,6022,2020,5,79500000,213969968,7
3,90000000,337.346,419074646,124.0,7.2,5392,2020,1,95400000,444219124,7
4,42000000,253.895,30234182,110.0,7.0,3216,2020,5,44520000,32048232,7
...,...,...,...,...,...,...,...,...,...,...,...
95,250000000,88.028,933959197,153.0,7.7,13414,2009,7,314725000,1175761233,8
96,160000000,83.605,1148461807,144.0,6.9,9406,2018,7,176880000,1269624527,7
97,150000000,96.360,259239658,164.0,7.5,8790,2017,4,169350000,292681573,8
98,28000000,91.249,39514713,96.0,6.9,1615,1993,7,54112800,76366134,7
99,13500000,83.715,89203432,88.0,6.3,1781,2019,11,14569200,96268343,6

EXPORT DATA

In [17]:
raw_data.to_csv('clean_data.csv', header=True, index=False)

In [18]:
test = pd.read_csv('clean_data.csv')
test.head()

,BUDGET,POPULARITY,REVENUE,RUNTIME,VOTE_AVERAGE,VOTE_COUNT,release_year,release_month,New_Budget,New_Revenue,New_Vote_Avg
0,200000000,936.725,57000000,115.0,7.3,2445,2020,4,212000000,60420000,7
1,17000000,641.633,35878266,114.0,7.1,602,2020,7,18020000,38030961,7
2,75000000,361.237,201858461,109.0,7.2,6022,2020,5,79500000,213969968,7
3,90000000,337.346,419074646,124.0,7.2,5392,2020,1,95400000,444219124,7
4,42000000,253.895,30234182,110.0,7.0,3216,2020,5,44520000,32048232,7